DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  last_online TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
);